package com.seggellion.britannia_mod.gametest;

import com.seggellion.britannia_mod.BritanniaMod;
import com.seggellion.britannia_mod.blockrestore.BrokenBlockData;
import com.seggellion.britannia_mod.blockrestore.BrokenBlockDataStorage;
import com.seggellion.britannia_mod.item.PurityOreItem;
import com.seggellion.britannia_mod.item.UOMetalToolMaterial;
import com.seggellion.britannia_mod.mining.MiningSkill;
import com.seggellion.britannia_mod.registry.BlockRegistry;
import com.seggellion.britannia_mod.resource.ResourceCatalog;
import com.seggellion.britannia_mod.resource.ResourceDefinition;
import com.seggellion.britannia_mod.resource.placement.MaterializationService;
import com.seggellion.britannia_mod.resource.placement.PlacementPlanner;
import com.seggellion.britannia_mod.resource.placement.PlannedDeposit;
import com.seggellion.britannia_mod.resource.shape.ShapeRotation;
import com.seggellion.britannia_mod.registry.ItemRegistry;
import com.seggellion.britannia_mod.registry.ToolRegistry;
import com.seggellion.britannia_mod.skill.SkillManager;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestAssertException;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Mining milestone 5: Silver end to end — gated at 55.0, mined through the managed flow into the
 * existing purity/refining identity, restored by the existing scheduler, and generated by the
 * planner-driven vertical-layered shape.
 */
@GameTestHolder(BritanniaMod.MODID)
@PrefixGameTestTemplate(false)
public final class SilverMiningGameTests {
    private static final String TEMPLATE = "service_npc_spawn_test_empty";

    private SilverMiningGameTests() {
    }

    private static ServerPlayer miner(GameTestHelper helper, float miningSkill) {
        ServerPlayer player = helper.makeMockServerPlayerInLevel();
        player.setGameMode(GameType.SURVIVAL);
        player.getInventory().clearContent();
        player.setItemInHand(InteractionHand.MAIN_HAND, new ItemStack(ToolRegistry.PICKAXE.get()));
        SkillManager.applyConfirmedValue(player, MiningSkill.SKILL_ID, miningSkill);
        return player;
    }

    private static List<ItemEntity> dropsNear(GameTestHelper helper, BlockPos absolute) {
        return helper.getLevel().getEntitiesOfClass(ItemEntity.class, new AABB(absolute).inflate(3.0));
    }

    private static void check(boolean condition, String message) {
        if (!condition) {
            throw new GameTestAssertException(message);
        }
    }

    @GameTest(template = TEMPLATE)
    public static void silverIsDeniedJustBelowTheThreshold(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos relative = new BlockPos(1, 1, 1);
        BlockPos absolute = helper.absolutePos(relative);
        helper.setBlock(relative, BlockRegistry.SILVER_ORE.get());
        ServerPlayer player = miner(helper, 54.9f);

        check(!player.gameMode.destroyBlock(absolute), "54.9 Mining must not break Silver");
        helper.assertBlockPresent(BlockRegistry.SILVER_ORE.get(), relative);
        check(dropsNear(helper, absolute).isEmpty(), "denied Silver must drop nothing");
        check(!BrokenBlockDataStorage.get(level).getBrokenBlocks().containsKey(absolute),
                "denied Silver must schedule no restoration");
        helper.succeed();
    }

    /** 55.0 exactly: mines, drops the established Silver purity ore, schedules one restoration. */
    @GameTest(template = TEMPLATE)
    public static void silverMinesAtTheThresholdIntoItsExistingIdentity(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos relative = new BlockPos(1, 1, 1);
        BlockPos absolute = helper.absolutePos(relative);
        helper.setBlock(relative, BlockRegistry.SILVER_ORE.get());
        // Silver is 55/15/95: qualifying at 55 only buys a coin toss, so a deterministic
        // harvest assertion stands at MaxSkill where the check is a certainty.
        ServerPlayer player = miner(helper, 95.0f);

        player.gameMode.destroyBlock(absolute);

        helper.assertBlockNotPresent(BlockRegistry.SILVER_ORE.get(), relative);
        List<ItemEntity> drops = dropsNear(helper, absolute);
        check(drops.size() == 1, "expected exactly one Silver drop, found " + drops.size());

        ItemStack dropped = drops.getFirst().getItem();
        check(dropped.getItem() instanceof PurityOreItem, "Silver must drop the purity ore item");
        PurityOreItem ore = (PurityOreItem) dropped.getItem();
        check("Silver ore".equals(ore.getOreType(dropped)),
                "drop must carry the Silver ore identity, got " + ore.getOreType(dropped));
        int purity = ore.getPurity(dropped);
        check(purity >= 1 && purity <= 5, "purity must be in the established 1-5 range, got " + purity);

        BrokenBlockData record = BrokenBlockDataStorage.get(level).getBrokenBlocks().get(absolute);
        check(record != null, "an authorized Silver break must schedule exactly one restoration");
        check(record.originalState.is(BlockRegistry.SILVER_ORE.get()),
                "restoration must remember Silver, not the replacement block");
        helper.succeed();
    }

    /** The pending Silver restoration must survive a save/load round trip. */
    @GameTest(template = TEMPLATE)
    public static void pendingSilverRestorationSurvivesSaveAndLoad(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos relative = new BlockPos(1, 1, 1);
        BlockPos absolute = helper.absolutePos(relative);
        helper.setBlock(relative, BlockRegistry.SILVER_ORE.get());
        ServerPlayer player = miner(helper, 95.0f);
        player.gameMode.destroyBlock(absolute);

        BrokenBlockDataStorage storage = BrokenBlockDataStorage.get(level);
        check(storage.getBrokenBlocks().containsKey(absolute), "precondition: Silver was scheduled");

        CompoundTag saved = storage.save(new CompoundTag(), level.registryAccess());
        BrokenBlockDataStorage reloaded = new BrokenBlockDataStorage(saved, level.registryAccess());

        BrokenBlockData record = reloaded.getBrokenBlocks().get(absolute);
        check(record != null, "the Silver restoration was lost across save/load");
        check(record.originalState.is(BlockRegistry.SILVER_ORE.get()),
                "the reloaded restoration forgot it was Silver");
        helper.succeed();
    }

    /**
     * The refining chain, asserted where the registries are live: the forge strips " ore" from the
     * mined item's type and resolves the metal, which must be the existing Silver identity rather
     * than a new one.
     */
    @GameTest(template = TEMPLATE)
    public static void silverRefinesIntoTheExistingIngot(GameTestHelper helper) {
        UOMetalToolMaterial material = UOMetalToolMaterial.getMaterialByName(
                "Silver ore".toLowerCase(java.util.Locale.ROOT).replace(" ore", ""));

        check(material == UOMetalToolMaterial.SILVER, "mined Silver must resolve to the Silver metal");
        check(material.getIngotSupplier().get() == ItemRegistry.SILVER_INGOT.get(),
                "refining must yield the existing silver ingot, not a second identity");

        // Owner decision 2026-08-14: exactly one Silver metal exists. A second one appearing here
        // would mean the retired High-Purity variant had been revived as a separate material.
        check(java.util.Arrays.stream(UOMetalToolMaterial.values())
                        .filter(metal -> metal.getMetalName().contains("silver")).count() == 1,
                "there must be exactly one Silver metal");
        helper.succeed();
    }

    /**
     * Placement: silver's configured shape really does produce silver ore in rock.
     *
     * <p>Rewritten at milestone 3, and the rewrite is the point. The old version called
     * {@code VerticalLayeredVein.generate} directly, and that shape placed only into
     * {@code isAir()} — so silver could generate in a cave and nowhere else, and this test passed
     * only because the template it ran in was empty. The planner no longer looks at the world at
     * all, so the cells are laid into host rock here, which is where silver is supposed to be.
     */
    @GameTest(template = TEMPLATE)
    public static void silverPlansAndMaterialisesIntoHostRock(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos center = helper.absolutePos(new BlockPos(2, 2, 2));

        ResourceDefinition silver = ResourceCatalog.instance().byPath("silver").orElseThrow();
        PlannedDeposit deposit = PlacementPlanner.planCuratedVein(
                silver, level.dimension().location().toString(), center, 2, ShapeRotation.ZW);

        check(deposit.count() > 0, "the silver planner produced no cells at all");

        // Give every planned cell a legitimate host. Without this the deposit is correctly refused,
        // which is the milestone-3 behaviour: air is not host rock.
        for (BlockPos planned : deposit.positions()) {
            level.setBlock(planned, Blocks.STONE.defaultBlockState(), 2);
        }

        MaterializationService.Result result = MaterializationService.materialize(level, deposit);
        check(result.placed() == deposit.count(),
                "every planned cell had a host, so every one should have been written: placed "
                        + result.placed() + " of " + deposit.count()
                        + " (" + result.describeRejections() + ")");

        for (BlockPos planned : deposit.positions()) {
            check(level.getBlockState(planned).is(BlockRegistry.SILVER_ORE.get()),
                    "a planned cell at " + planned.toShortString() + " is not silver ore");
        }

        // Running it again re-derives the same seed, re-plans the same cells, finds them already
        // correct, and writes nothing. That is placement-level idempotence.
        MaterializationService.Result second = MaterializationService.materialize(level, deposit);
        check(second.placed() == 0, "a repeat placement must write nothing, wrote " + second.placed());
        check(second.rejected(MaterializationService.Rejection.ALREADY_PRESENT) == deposit.count(),
                "a repeat placement must find every cell already correct");
        helper.succeed();
    }
}
