package com.seggellion.britannia_mod.gametest;

import com.seggellion.britannia_mod.BritanniaMod;
import com.seggellion.britannia_mod.blockrestore.BrokenBlockData;
import com.seggellion.britannia_mod.blockrestore.BrokenBlockDataStorage;
import com.seggellion.britannia_mod.features.VerticalLayeredVein;
import com.seggellion.britannia_mod.item.PurityOreItem;
import com.seggellion.britannia_mod.item.UOMetalToolMaterial;
import com.seggellion.britannia_mod.mining.MiningSkill;
import com.seggellion.britannia_mod.registry.BlockRegistry;
import com.seggellion.britannia_mod.registry.ItemRegistry;
import com.seggellion.britannia_mod.registry.ToolRegistry;
import com.seggellion.britannia_mod.skill.SkillManager;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestAssertException;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Mining milestone 5: Silver end to end — gated at 55.0, mined through the managed flow into the
 * existing purity/refining identity, restored by the existing scheduler, and generated by the
 * existing vertical-layered vein implementation.
 */
@GameTestHolder(BritanniaMod.MODID)
@PrefixGameTestTemplate(false)
public final class SilverMiningGameTests {
    private static final String TEMPLATE = "service_npc_spawn_test_empty";

    private SilverMiningGameTests() {
    }

    private static ServerPlayer miner(GameTestHelper helper, float miningSkill) {
        ServerPlayer player = helper.makeMockServerPlayerInLevel();
        player.setGameMode(GameType.SURVIVAL);
        player.getInventory().clearContent();
        player.setItemInHand(InteractionHand.MAIN_HAND, new ItemStack(ToolRegistry.PICKAXE.get()));
        SkillManager.applyConfirmedValue(player, MiningSkill.SKILL_ID, miningSkill);
        return player;
    }

    private static List<ItemEntity> dropsNear(GameTestHelper helper, BlockPos absolute) {
        return helper.getLevel().getEntitiesOfClass(ItemEntity.class, new AABB(absolute).inflate(3.0));
    }

    private static void check(boolean condition, String message) {
        if (!condition) {
            throw new GameTestAssertException(message);
        }
    }

    @GameTest(template = TEMPLATE)
    public static void silverIsDeniedJustBelowTheThreshold(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos relative = new BlockPos(1, 1, 1);
        BlockPos absolute = helper.absolutePos(relative);
        helper.setBlock(relative, BlockRegistry.SILVER_ORE.get());
        ServerPlayer player = miner(helper, 54.9f);

        check(!player.gameMode.destroyBlock(absolute), "54.9 Mining must not break Silver");
        helper.assertBlockPresent(BlockRegistry.SILVER_ORE.get(), relative);
        check(dropsNear(helper, absolute).isEmpty(), "denied Silver must drop nothing");
        check(!BrokenBlockDataStorage.get(level).getBrokenBlocks().containsKey(absolute),
                "denied Silver must schedule no restoration");
        helper.succeed();
    }

    /** 55.0 exactly: mines, drops the established Silver purity ore, schedules one restoration. */
    @GameTest(template = TEMPLATE)
    public static void silverMinesAtTheThresholdIntoItsExistingIdentity(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos relative = new BlockPos(1, 1, 1);
        BlockPos absolute = helper.absolutePos(relative);
        helper.setBlock(relative, BlockRegistry.SILVER_ORE.get());
        ServerPlayer player = miner(helper, 55.0f);

        player.gameMode.destroyBlock(absolute);

        helper.assertBlockNotPresent(BlockRegistry.SILVER_ORE.get(), relative);
        List<ItemEntity> drops = dropsNear(helper, absolute);
        check(drops.size() == 1, "expected exactly one Silver drop, found " + drops.size());

        ItemStack dropped = drops.getFirst().getItem();
        check(dropped.getItem() instanceof PurityOreItem, "Silver must drop the purity ore item");
        PurityOreItem ore = (PurityOreItem) dropped.getItem();
        check("Silver ore".equals(ore.getOreType(dropped)),
                "drop must carry the Silver ore identity, got " + ore.getOreType(dropped));
        int purity = ore.getPurity(dropped);
        check(purity >= 1 && purity <= 5, "purity must be in the established 1-5 range, got " + purity);

        BrokenBlockData record = BrokenBlockDataStorage.get(level).getBrokenBlocks().get(absolute);
        check(record != null, "an authorized Silver break must schedule exactly one restoration");
        check(record.originalState.is(BlockRegistry.SILVER_ORE.get()),
                "restoration must remember Silver, not the replacement block");
        helper.succeed();
    }

    /** The pending Silver restoration must survive a save/load round trip. */
    @GameTest(template = TEMPLATE)
    public static void pendingSilverRestorationSurvivesSaveAndLoad(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos relative = new BlockPos(1, 1, 1);
        BlockPos absolute = helper.absolutePos(relative);
        helper.setBlock(relative, BlockRegistry.SILVER_ORE.get());
        ServerPlayer player = miner(helper, 60.0f);
        player.gameMode.destroyBlock(absolute);

        BrokenBlockDataStorage storage = BrokenBlockDataStorage.get(level);
        check(storage.getBrokenBlocks().containsKey(absolute), "precondition: Silver was scheduled");

        CompoundTag saved = storage.save(new CompoundTag(), level.registryAccess());
        BrokenBlockDataStorage reloaded = new BrokenBlockDataStorage(saved, level.registryAccess());

        BrokenBlockData record = reloaded.getBrokenBlocks().get(absolute);
        check(record != null, "the Silver restoration was lost across save/load");
        check(record.originalState.is(BlockRegistry.SILVER_ORE.get()),
                "the reloaded restoration forgot it was Silver");
        helper.succeed();
    }

    /**
     * The refining chain, asserted where the registries are live: the forge strips " ore" from the
     * mined item's type and resolves the metal, which must be the existing Silver identity rather
     * than a new one.
     */
    @GameTest(template = TEMPLATE)
    public static void silverRefinesIntoTheExistingIngot(GameTestHelper helper) {
        UOMetalToolMaterial material = UOMetalToolMaterial.getMaterialByName(
                "Silver ore".toLowerCase(java.util.Locale.ROOT).replace(" ore", ""));

        check(material == UOMetalToolMaterial.SILVER, "mined Silver must resolve to the Silver metal");
        check(material.getIngotSupplier().get() == ItemRegistry.SILVER_INGOT.get(),
                "refining must yield the existing silver ingot, not a second identity");

        // Owner decision 2026-08-14: exactly one Silver metal exists. A second one appearing here
        // would mean the retired High-Purity variant had been revived as a separate material.
        check(java.util.Arrays.stream(UOMetalToolMaterial.values())
                        .filter(metal -> metal.getMetalName().contains("silver")).count() == 1,
                "there must be exactly one Silver metal");
        helper.succeed();
    }

    /**
     * Placement: the existing vertical-layered vein implementation that {@code /populateores silver}
     * routes to actually produces Silver ore blocks. Uses a deliberately small radius so the vein
     * stays inside this test's own space.
     */
    @GameTest(template = TEMPLATE)
    public static void silverVeinGeneratorPlacesSilverOre(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos center = helper.absolutePos(new BlockPos(2, 2, 2));
        Map<BlockPos, BlockState> replaced = new HashMap<>();

        int placed = VerticalLayeredVein.generate(
                level, center, 3, BlockRegistry.SILVER_ORE.get(), "ZW", replaced);

        check(placed > 0, "the Silver vein generator placed nothing");
        long silverBlocks = replaced.keySet().stream()
                .filter(pos -> level.getBlockState(pos).is(BlockRegistry.SILVER_ORE.get()))
                .count();
        check(silverBlocks > 0, "no Silver ore is present where the vein reported placements");
        check(replaced.size() == placed,
                "every placement must record its original block so /undoores can reverse it");
        helper.succeed();
    }
}
