package com.seggellion.britannia_mod.skill.crafting;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import net.minecraft.client.renderer.block.model.BlockModel;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Patch18WeaponAssetsTest {
    private static final List<String> ITEMS = List.of("dagger", "viking_sword", "katana", "rapier",
            "halberd", "decorative_shield");

    private JsonObject resource(String path) throws Exception {
        try (var stream = getClass().getResourceAsStream(path)) {
            assertNotNull(stream, path);
            return JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8)).getAsJsonObject();
        }
    }

    @Test
    void modelsParseInTheActualMinecraftVersionAndAllReferencesResolve() throws Exception {
        for (String id : ITEMS) {
            JsonObject model = resource("/assets/britannia_mod/models/item/" + id + ".json");
            assertDoesNotThrow(() -> BlockModel.fromString(model.toString()), id);
            assertFalse(model.getAsJsonArray("elements").isEmpty(), id);
            assertEquals("minecraft:block/block", model.get("parent").getAsString(), id);
            for (var texture : model.getAsJsonObject("textures").entrySet()) {
                String path = texture.getValue().getAsString();
                assertEquals(path.toLowerCase(java.util.Locale.ROOT), path);
                assertNotNull(getClass().getResource("/assets/" + path.replace(":", "/textures/") + ".png"), path);
            }
            for (String context : List.of("gui", "ground", "fixed", "firstperson_righthand",
                    "firstperson_lefthand", "thirdperson_righthand", "thirdperson_lefthand")) {
                assertTrue(model.getAsJsonObject("display").has(context), id + ": " + context);
            }
            for (var element : model.getAsJsonArray("elements")) {
                for (var face : element.getAsJsonObject().getAsJsonObject("faces").entrySet()) {
                    JsonObject value = face.getValue().getAsJsonObject();
                    assertEquals("#0", value.get("texture").getAsString(), id);
                    for (var coordinate : value.getAsJsonArray("uv")) {
                        assertTrue(coordinate.getAsDouble() >= 0 && coordinate.getAsDouble() <= 16, id + " UV");
                    }
                }
            }
            assertNotNull(resource("/assets/britannia_mod/lang/en_us.json").get("item.britannia_mod." + id));
        }
        JsonObject blocking = resource("/assets/britannia_mod/models/item/decorative_shield_blocking.json");
        assertDoesNotThrow(() -> BlockModel.fromString(blocking.toString()));
        assertEquals("britannia_mod:item/decorative_shield", blocking.get("parent").getAsString());
    }

    @Test
    void importedRecipesKeepEstablishedCostsAndExplicitlyMarkAnalogueDecisions() {
        int[] ingots = {3, 14, 8, 8, 20, 14};
        float[] skill = {0, 24.3f, 44.1f, 36.7f, 39.1f, 0};
        for (int i = 0; i < ITEMS.size(); i++) {
            CraftableDef def = CraftableRegistry.get(ITEMS.get(i));
            assertEquals("britannia_mod:" + ITEMS.get(i), def.resultItem().toString());
            assertEquals(ingots[i], def.ingredients().getFirst().amount());
            assertEquals(skill[i], def.minimumBlacksmithy());
            assertEquals(1, def.outputCount());
            assertTrue(def.recyclable());
            assertFalse(def.batchCrafting());
            assertFalse(def.requiresLearnedRecipe());
            assertEquals(ITEMS.get(i).equals("rapier") || ITEMS.get(i).equals("decorative_shield"), def.provisional());
        }
    }

    /**
     * Merge regression, 2026-09-09 (public patch-18 lineage into the Rowan lineage).
     *
     * <p>Both lineages shipped {@code tools/new-assets/import_patch18_weapons.py} with the same
     * import logic and a different manifest: the public side wrote a portable one under
     * {@code tools/} whose {@code source_root} is the relative label {@code "weapons"}, the Rowan
     * side wrote one under {@code docs/new-assets/} whose {@code source_root} is one machine's
     * absolute disk path. The merge kept the portable manifest as the one the tool regenerates and
     * {@code --check} verifies, because a manifest that names a private drive can only ever be
     * verified on that drive, and kept the documentation copy because
     * {@code docs/new-assets/PATCH18_WEAPON_INTEGRATION.md} presents it as the source inventory.
     *
     * <p>So exactly one of the two is now regenerated by the importer, and the other is a document
     * nothing rewrites: the file hashes can diverge and {@code --check} would keep passing while
     * the published inventory quietly described different bytes. The {@code source_root} fields are
     * expected to differ -- that is the whole point of the split -- but the seventeen SHA-256
     * entries are one fact recorded twice, and this holds them to it.
     */
    @Test
    void theTwoRecordedSourceInventoriesAgreeOnEverySuppliedFile() throws Exception {
        Path project = Path.of(System.getProperty("britannia.projectDir", "."));
        Path regenerated = project.resolve("tools/new-assets/patch18_weapon_assets.json");
        Path documented = project.resolve("docs/new-assets/PATCH18_WEAPON_ASSETS.json");
        assertTrue(Files.isRegularFile(regenerated), regenerated + " is missing");
        assertTrue(Files.isRegularFile(documented), documented + " is missing");

        JsonObject regeneratedFiles = JsonParser.parseString(Files.readString(regenerated))
                .getAsJsonObject().getAsJsonObject("files");
        JsonObject documentedFiles = JsonParser.parseString(Files.readString(documented))
                .getAsJsonObject().getAsJsonObject("files");

        assertEquals(17, regeneratedFiles.size(),
                "the importer accounts for all 17 supplied source files");
        assertEquals(regeneratedFiles, documentedFiles,
                "the documented weapon source inventory has drifted from the one the importer"
                        + " regenerates and --check verifies; rerun the importer and update the doc");

        assertEquals("weapons", JsonParser.parseString(Files.readString(regenerated))
                        .getAsJsonObject().get("source_root").getAsString(),
                "the regenerated manifest must stay portable: a source_root naming one machine's"
                        + " disk makes --check unrunnable anywhere else");
    }
}
