package com.seggellion.britannia_mod.bannerdyeing;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.seggellion.britannia_mod.dye.colour.ColourMath;
import com.seggellion.britannia_mod.dye.colour.LinearSrgb;
import com.seggellion.britannia_mod.dye.colour.OklabColour;
import com.seggellion.britannia_mod.dye.colour.SrgbColour;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

class ColourMathTest {
    /*
     * Reference fixtures were calculated independently from the W3C CSS Color 4 sample sRGB
     * linearization algorithm and Bjorn Ottosson's published 2021-01-25 linear-sRGB/OKLab matrices,
     * then stored here as literals. They are not generated by ColourMath during the test.
     * https://www.w3.org/TR/css-color-4/#color-conversion-code
     * https://bottosson.github.io/posts/oklab/
     */
    static Stream<Arguments> oklabReferences() {
        return Stream.of(
                Arguments.of("#000000", 0.000000000000, 0.000000000000, 0.000000000000),
                Arguments.of("#FFFFFF", 0.999999993474, 0.000000000081, 0.000000037274),
                Arguments.of("#FF0000", 0.627955360615, 0.224863061066, 0.125846298531),
                Arguments.of("#00FF00", 0.866439611536, -0.233887574188, 0.179498479897),
                Arguments.of("#0000FF", 0.452013718385, -0.032456984169, -0.311528147678),
                Arguments.of("#808080", 0.599870801707, 0.000000000049, 0.000000022360),
                Arguments.of("#965B55", 0.535774130868, 0.070735031423, 0.034910318236),
                Arguments.of("#8ED8E8", 0.839298158427, -0.064401640971, -0.041486343675),
                Arguments.of("#D6CDB7", 0.849684132809, 0.000882706717, 0.031359412383),
                Arguments.of("#C8B89E", 0.789139113720, 0.006966257072, 0.039357769196),
                Arguments.of("#D8CCAE", 0.847167033741, 0.000884381263, 0.042407077217),
                Arguments.of("#E7DCC9", 0.898182201465, 0.004178999312, 0.027851471628));
    }

    static Stream<Arguments> transferReferences() {
        return Stream.of(
                Arguments.of(0, 0.0),
                Arguments.of(1, 0.0003035269835488375),
                Arguments.of(10, 0.003035269835488375),
                Arguments.of(11, 0.003346535763899161),
                Arguments.of(128, 0.21586050011389926),
                Arguments.of(255, 1.0));
    }

    @Test
    void canonicalSrgbParsingCoversBlackWhitePrimariesGreyAndBoundaries() {
        assertEquals(new SrgbColour(0, 0, 0), ColourMath.parseCanonicalSrgb("#000000"));
        assertEquals(new SrgbColour(255, 255, 255), ColourMath.parseCanonicalSrgb("#FFFFFF"));
        assertEquals(new SrgbColour(255, 0, 0), ColourMath.parseCanonicalSrgb("#FF0000"));
        assertEquals(new SrgbColour(0, 255, 0), ColourMath.parseCanonicalSrgb("#00FF00"));
        assertEquals(new SrgbColour(0, 0, 255), ColourMath.parseCanonicalSrgb("#0000FF"));
        assertEquals(new SrgbColour(128, 128, 128), ColourMath.parseCanonicalSrgb("#808080"));
        assertEquals(new SrgbColour(1, 10, 127), ColourMath.parseCanonicalSrgb("#010A7F"));
    }

    @Test
    void malformedAndLowercaseSrgbAreRejectedWithoutClamping() {
        for (String invalid : List.of("#ffffff", "#FFFFF", "FFFFFF", "#GG0000", "#00000000", "")) {
            assertThrows(IllegalArgumentException.class, () -> ColourMath.parseCanonicalSrgb(invalid), invalid);
        }
        assertThrows(IllegalArgumentException.class, () -> new SrgbColour(-1, 0, 0));
        assertThrows(IllegalArgumentException.class, () -> new SrgbColour(0, 0, 256));
    }

    @ParameterizedTest
    @MethodSource("transferReferences")
    void inverseSrgbTransferMatchesIndependentReferences(int channel, double expected) {
        double actual = ColourMath.toLinearChannel(channel);
        assertEquals(expected, actual, 1.0e-15);
        assertTrue(Double.isFinite(actual));
        assertTrue(actual >= 0.0 && actual <= 1.0);
    }

    @Test
    void normalizedTransferRejectsNonFiniteAndOutOfRangeValues() {
        for (double invalid : List.of(-0.0001, 1.0001, Double.NaN,
                Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY)) {
            assertThrows(IllegalArgumentException.class, () -> ColourMath.toLinearChannel(invalid));
        }
    }

    @ParameterizedTest
    @MethodSource("oklabReferences")
    void oklabMatchesIndependentReferenceFixtures(String srgb, double lightness, double a, double b) {
        OklabColour actual = ColourMath.toOklab(srgb);
        assertEquals(lightness, actual.lightness(), ColourMath.REFERENCE_TEST_TOLERANCE);
        assertEquals(a, actual.a(), ColourMath.REFERENCE_TEST_TOLERANCE);
        assertEquals(b, actual.b(), ColourMath.REFERENCE_TEST_TOLERANCE);
        assertTrue(Double.isFinite(actual.lightness()));
        assertTrue(Double.isFinite(actual.a()));
        assertTrue(Double.isFinite(actual.b()));
    }

    @Test
    void linearRgbToOklabHandlesValuesExtremelyCloseToZero() {
        OklabColour actual = ColourMath.toOklab(new LinearSrgb(1.0e-15, 0.0, 0.0));
        assertEquals(new OklabColour(0.0, 0.0, 0.0), actual);
    }

    @Test
    void distanceIsZeroSymmetricFiniteAndOrdersKnownPairs() {
        OklabColour red = ColourMath.toOklab("#FF0000");
        OklabColour mutedRed = ColourMath.toOklab("#965B55");
        OklabColour blue = ColourMath.toOklab("#0000FF");
        assertEquals(0.0, ColourMath.distance(red, red));
        assertEquals(ColourMath.distance(red, mutedRed), ColourMath.distance(mutedRed, red), 0.0);
        assertTrue(ColourMath.distance(red, mutedRed) >= 0.0);
        assertTrue(Double.isFinite(ColourMath.distance(red, blue)));
        assertTrue(ColourMath.distance(red, mutedRed) < ColourMath.distance(red, blue));
    }

    @Test
    void tieEpsilonIncludesTinyDifferencesAndRejectsLargerOnes() {
        assertTrue(ColourMath.distancesTie(0.1, 0.1 + ColourMath.TIE_EPSILON * 0.5));
        assertFalse(ColourMath.distancesTie(0.1, 0.1 + ColourMath.TIE_EPSILON * 2.0));
        assertThrows(IllegalArgumentException.class, () -> ColourMath.distancesTie(-0.1, 0.1));
        assertThrows(IllegalArgumentException.class, () -> ColourMath.distancesTie(Double.NaN, 0.1));
    }
}
