package com.seggellion.britannia_mod.service.spawn;

public enum ServiceNpcSpawnValidationError {
    NONE,
    NO_CHANGE,
    UNAUTHORIZED,
    WRONG_MENU,
    WRONG_OWNER,
    CONTAINER_MISMATCH,
    WRONG_DIMENSION,
    TOO_FAR,
    WRONG_POSITION,
    MISSING_BLOCK,
    WRONG_BLOCK,
    WRONG_BLOCK_ENTITY,
    UUID_MISMATCH,
    STALE_REVISION,
    REGISTRY_UNAVAILABLE,
    CITY_UNAVAILABLE,
    TYPE_UNAVAILABLE,
    TYPE_INACTIVE,
    TYPE_NOT_SPAWNABLE,
    OVERSIZED_FIELD,
    PAYLOAD_TOO_LARGE,
    REVISION_OVERFLOW,
    PENDING_STORE_ERROR,
    CLAIM_STORE_ERROR,
    INTERNAL_ERROR
}
