package com.seggellion.britannia_mod.resource.deposit;

import java.util.Locale;
import java.util.Optional;

/**
 * Where a deposit came from, which decides how its identity is derived.
 *
 * <p>Part of the immutable metadata: a deposit does not change source, and two deposits that would
 * otherwise hash alike are kept apart by it. It is also what lets diagnostics tell an operator
 * whether a deposit is something the world generated, something Rails curated, something an
 * administrator placed, or something a migration adopted.
 */
public enum DepositSource {
    /** Generated by world generation from the world seed and a grid cell. Not yet implemented. */
    NATURAL,
    /** Imported from a curated Rails vein row. */
    RAILS,
    /** Placed deliberately by an operator; its id is generated once and persisted. */
    ADMIN,
    /** Adopted from existing terrain by a bounded migration batch. Milestone 8. */
    RETROFIT;

    public String id() {
        return name().toLowerCase(Locale.ROOT);
    }

    public static Optional<DepositSource> byId(String id) {
        if (id == null) return Optional.empty();
        for (DepositSource source : values()) {
            if (source.id().equals(id.toLowerCase(Locale.ROOT))) return Optional.of(source);
        }
        return Optional.empty();
    }
}
