package com.seggellion.britannia_mod.mining;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.function.DoubleUnaryOperator;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Milestone 4 balance proof: the shipped Mining gain math must put a reasonable progression route
 * inside the approved 17,100–18,900 activation window for 0.0 → 100.0, keep Stone trainable
 * forever, and make appropriate material the better path. Deterministic expected values, so this
 * is a real acceptance gate rather than a sampled estimate.
 */
class MiningCalibrationTest {

    private static final Path PROJECT = Path.of(System.getProperty("britannia.projectDir", "."));
    private static final double TARGET = 18_000.0;
    private static final double LOWER_BOUND = 17_100.0;
    private static final double UPPER_BOUND = 18_900.0;

    private static MineableCatalog catalog;
    private static DoubleUnaryOperator recommended;

    @BeforeAll
    static void loadShippedCatalog() throws Exception {
        catalog = MineableCatalog.parse(Files.newBufferedReader(
                PROJECT.resolve("src/main/resources/data/britannia_mod/mining/mineables.json")));
        recommended = MiningProgressionCalculator.bestAvailableChallenge(catalog);
    }

    @Test
    void recommendedRouteLandsInsideTheApprovedActivationWindow() {
        double total = MiningProgressionCalculator.expectedActivations(0.0, 100.0, recommended);
        assertTrue(total >= LOWER_BOUND && total <= UPPER_BOUND,
                "recommended route expects " + Math.round(total)
                        + " activations, outside the approved " + (long) LOWER_BOUND + "-"
                        + (long) UPPER_BOUND + " window");
    }

    @Test
    void stoneOnlyRemainsPossibleButIsAWorsePathThanAppropriateMaterial() {
        double stoneOnly = MiningProgressionCalculator.expectedActivations(
                0.0, 100.0, MiningProgressionCalculator.stoneOnlyChallenge());
        double route = MiningProgressionCalculator.expectedActivations(0.0, 100.0, recommended);

        assertTrue(Double.isFinite(stoneOnly),
                "Stone must never stop granting Mining, at any skill (design §9.2)");
        assertTrue(stoneOnly > route,
                "harder material must be the better progression path: stone-only " + Math.round(stoneOnly)
                        + " vs recommended " + Math.round(route));
        assertTrue(MiningSkill.gainChance(99.9f, 0.0f) > 0.0f,
                "Stone must still roll at 99.9 Mining");
    }

    @Test
    void gainChanceHonoursItsBoundaries() {
        assertEquals(0.0f, MiningSkill.gainChance(100.0f, 0.0f), 0.0f, "no gain at the cap");
        assertEquals(0.0f, MiningSkill.gainChance(Float.NaN, 0.0f), 0.0f, "unavailable skill never rolls");
        assertEquals(MiningSkill.BASE_CHANCE, MiningSkill.gainChance(0.0f, 0.0f), 1.0e-6f,
                "a fresh miner on Stone rolls the base chance");

        // Material value decays as you outgrow a resource, but never past the floor.
        assertEquals(1.0f, MiningSkill.materialFactor(55.0f, 55.0f), 1.0e-6f);
        assertEquals(1.0f, MiningSkill.materialFactor(10.0f, 55.0f), 1.0e-6f,
                "a resource above your skill carries full value");
        assertEquals(0.9f, MiningSkill.materialFactor(65.0f, 55.0f), 1.0e-6f);
        assertEquals(MiningSkill.MINIMUM_MATERIAL_FACTOR, MiningSkill.materialFactor(99.0f, 0.0f), 1.0e-6f,
                "the floor keeps trailing resources trainable");

        // Rising skill is monotonically harder on one fixed resource.
        float previous = Float.MAX_VALUE;
        for (int tenth = 0; tenth < 1000; tenth++) {
            float chance = MiningSkill.gainChance(tenth / 10.0f, 0.0f);
            assertTrue(chance <= previous, "gain chance must not rise with skill at " + tenth / 10.0f);
            previous = chance;
        }
    }

    @Test
    void appropriateMaterialBeatsAnOutgrownOneAtTheSameSkill() {
        float atTier = MiningSkill.gainChance(75.0f, 75.0f);
        float outgrown = MiningSkill.gainChance(75.0f, 0.0f);
        assertTrue(atTier > outgrown,
                "copper at 75 must out-train stone at 75: " + atTier + " vs " + outgrown);
    }

    /** Publishes the numbers the calibration report quotes, so the document cannot drift. */
    @Test
    void publishCalibrationTable() throws Exception {
        List<String> lines = new ArrayList<>();
        lines.add("Mining progression calibration (generated by MiningCalibrationTest)");
        lines.add("BASE_CHANCE=" + MiningSkill.BASE_CHANCE
                + "  GAIN_UNIT=" + MiningSkill.GAIN_UNIT
                + "  MATERIAL_DECAY_SPAN=" + MiningSkill.MATERIAL_DECAY_SPAN
                + "  MINIMUM_MATERIAL_FACTOR=" + MiningSkill.MINIMUM_MATERIAL_FACTOR);
        lines.add("");
        lines.add(String.format(Locale.ROOT, "%-14s %18s %18s", "band", "recommended", "stone-only"));

        double recommendedTotal = 0.0;
        double stoneTotal = 0.0;
        for (double[] band : MiningProgressionCalculator.BANDS) {
            double route = MiningProgressionCalculator.expectedActivations(band[0], band[1], recommended);
            double stone = MiningProgressionCalculator.expectedActivations(
                    band[0], band[1], MiningProgressionCalculator.stoneOnlyChallenge());
            recommendedTotal += route;
            stoneTotal += stone;
            lines.add(String.format(Locale.ROOT, "%-14s %18d %18d",
                    trim(band[0]) + "-" + trim(band[1]), Math.round(route), Math.round(stone)));
        }
        lines.add(String.format(Locale.ROOT, "%-14s %18d %18d",
                "TOTAL 0-100", Math.round(recommendedTotal), Math.round(stoneTotal)));
        lines.add("");
        lines.add("target window: " + (long) LOWER_BOUND + " - " + (long) UPPER_BOUND
                + " (18,000 +/-5%); deviation from 18,000: "
                + String.format(Locale.ROOT, "%+.2f%%", 100.0 * (recommendedTotal - TARGET) / TARGET));

        // Guildmaster training tops a skill out at 40.0, so record what buying that ceiling skips.
        double toTrainingCeiling =
                MiningProgressionCalculator.expectedActivations(0.0, 40.0, recommended);
        lines.add(String.format(Locale.ROOT,
                "guildmaster ceiling 40.0: field cost 0-40 = %d activations (%.1f%% of the journey);"
                        + " remaining 40-100 = %d",
                Math.round(toTrainingCeiling),
                100.0 * toTrainingCeiling / recommendedTotal,
                Math.round(recommendedTotal - toTrainingCeiling)));

        Path report = PROJECT.resolve("build/reports/mining/calibration.txt");
        Files.createDirectories(report.getParent());
        Files.write(report, lines);

        // The band sum must equal the whole-journey figure the acceptance test checks.
        assertEquals(MiningProgressionCalculator.expectedActivations(0.0, 100.0, recommended),
                recommendedTotal, 1.0e-6, "bands must partition the full journey");
    }

    private static String trim(double value) {
        return value == Math.rint(value)
                ? Integer.toString((int) value)
                : String.format(Locale.ROOT, "%.1f", value);
    }
}
