package com.seggellion.britannia_mod.bannerdyeing.admin;

public enum BannerAdminFailure {
    NONE,
    REGISTRY_UNAVAILABLE,
    DEFINITION_MISSING,
    DEFINITION_DISABLED,
    MATERIAL_MISSING,
    MATERIAL_DISABLED,
    PALETTE_MISSING,
    NATURAL_COLOUR_MISSING,
    COLOUR_MISSING,
    COLOUR_NOT_IN_MATERIAL,
    MOUNT_MISSING,
    MOUNT_DISABLED,
    UNSUPPORTED_MOUNT,
    INVALID_STATE,
    FACTORY_FAILURE
}
