package com.seggellion.britannia_mod.structure.placement;

/** Stable failure categories for non-mutating planning and transactional execution. */
public enum ShrinePlacementFailure {
    NONE,
    INVALID_ITEM,
    UNSUPPORTED_FAMILY,
    FAMILY_MISSING,
    VARIANT_MISSING,
    VARIANT_DISABLED,
    INCOMPATIBLE_VARIANT,
    INVALID_CLICKED_FACE,
    INVALID_FACING,
    WORLD_BOUND_FAILURE,
    REQUIRED_CHUNK_UNLOADED,
    TARGET_OCCUPIED,
    UNRELATED_STRUCTURE_CELL,
    PROTECTED_PLACEMENT,
    BLOCK_ENTITY_CREATION_FAILURE,
    PART_STATE_ENCODING_FAILURE,
    STATE_TRANSFER_FAILURE,
    BLOCK_SET_FAILURE,
    FINAL_VERIFICATION_FAILURE,
    SYNCHRONIZATION_FAILURE,
    UNEXPECTED_ROLLBACK_FAILURE
}
