package com.seggellion.britannia_mod.quest;

import com.mojang.logging.LogUtils;
import com.seggellion.britannia_mod.network.payload.QuestActionC2SPayload;
import net.minecraft.server.level.ServerPlayer;
import org.slf4j.Logger;

import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Structured, machine-readable tracing for quest actions (Milestone 2, findings S-1..S-12).
 *
 * <p>Before this existed, the single most common way for a quest to fail was
 * {@code QuestProxyService} answering 422 and logging <b>nothing at all</b>: the request never
 * reached Rails, no line was written, and the player simply saw nothing happen. Six distinct
 * causes collapsed into that one silent response. Every rejection now names its stage and a
 * machine-readable reason, and carries the client's correlation id, so a report of "player X
 * could not finish quest Y" is answerable from logs instead of inferred.
 *
 * <p>The correlation id (`request_uuid`) is generated by the client, echoed in these lines, and
 * forwarded to Rails, which logs it too. It is an opaque trace token: nothing is authorized by it.
 *
 * <p>The last rejection per player is also retained in memory so tests -- and, later, an operator
 * command -- can assert on the reason without scraping log files. The map is bounded and holds
 * only ids and reason codes, never payloads.
 */
public final class QuestActionTelemetry {
    private static final Logger LOGGER = LogUtils.getLogger();
    private static final int MAX_TRACKED_PLAYERS = 256;
    private static final Map<UUID, Rejection> LAST_REJECTION = new ConcurrentHashMap<>();

    /** Where in the pipeline a quest action died. */
    public enum Stage { SHAPE, NPC_RESOLVE, JOURNAL_GATE, DISPATCH, RESPONSE }

    public record Rejection(String requestUuid, String action, long questId, Stage stage,
                            String reason, int journalSize) {}

    private QuestActionTelemetry() {}

    public static void requested(ServerPlayer player, QuestActionC2SPayload request, String questGiverApiId) {
        LOGGER.info("event=quest_action_requested request_uuid={} action={} player_uuid={} quest_id={} "
                + "quest_giver_uuid={} quest_giver_api_id={}",
            requestUuid(request), action(request), playerUuid(player), questId(request),
            request == null ? "" : request.questGiverUuid(), safe(questGiverApiId));
    }

    public static void rejected(ServerPlayer player, QuestActionC2SPayload request, Stage stage,
                                String reason, int journalSize) {
        LOGGER.warn("event=quest_action_rejected request_uuid={} action={} player_uuid={} quest_id={} "
                + "stage={} reason={} journal_size={}",
            requestUuid(request), action(request), playerUuid(player), questId(request),
            stage, reason, journalSize);
        remember(player, new Rejection(requestUuid(request), action(request), questId(request),
            stage, reason, journalSize));
    }

    public static void result(ServerPlayer player, QuestActionC2SPayload request, int railsStatus,
                              boolean success, int grantedItemCount) {
        LOGGER.info("event=quest_action_result request_uuid={} action={} player_uuid={} quest_id={} "
                + "rails_status={} success={} granted_item_count={}",
            requestUuid(request), action(request), playerUuid(player), questId(request),
            railsStatus, success, grantedItemCount);
    }

    /** The most recent rejection for this player, for tests and diagnostics. */
    public static Optional<Rejection> lastRejection(UUID playerUuid) {
        return playerUuid == null ? Optional.empty() : Optional.ofNullable(LAST_REJECTION.get(playerUuid));
    }

    public static void clear(UUID playerUuid) {
        if (playerUuid != null) LAST_REJECTION.remove(playerUuid);
    }

    private static void remember(ServerPlayer player, Rejection rejection) {
        if (player == null) return;
        // Bounded: diagnostics must never become a leak. Dropping the history wholesale is
        // acceptable -- the log line above is the durable record; this is only a convenience.
        if (LAST_REJECTION.size() >= MAX_TRACKED_PLAYERS) LAST_REJECTION.clear();
        LAST_REJECTION.put(player.getUUID(), rejection);
    }

    private static String requestUuid(QuestActionC2SPayload request) {
        return request == null ? "" : safe(request.requestUuid());
    }

    private static String action(QuestActionC2SPayload request) {
        return request == null || request.action() == null ? "" : request.action().name();
    }

    private static long questId(QuestActionC2SPayload request) {
        return request == null ? 0L : request.questId();
    }

    private static String playerUuid(ServerPlayer player) {
        return player == null ? "" : player.getStringUUID();
    }

    private static String safe(String value) {
        if (value == null || value.isBlank()) return "";
        String cleaned = value.replaceAll("[\\p{Cntrl}]", "");
        return cleaned.substring(0, Math.min(cleaned.length(), 64));
    }
}
