package com.seggellion.britannia_mod.banner.item;

public enum BannerStateIssueKind {
    COMPONENT_MISSING,
    COMPONENT_DECODE_FAILURE,
    REGISTRY_UNAVAILABLE,
    DEFINITION_MISSING,
    DEFINITION_DISABLED,
    MATERIAL_MISSING,
    MATERIAL_DISABLED,
    PALETTE_MISSING,
    RESOLVED_COLOUR_MISSING,
    SOURCE_PIGMENT_MISSING,
    SOURCE_PIGMENT_DISABLED,
    MOUNT_MISSING,
    MOUNT_DISABLED,
    UNSUPPORTED_MOUNT,
    REPAIRABLE_MISSING_COLOUR,
    INVALID_ITEM,
    STALE_PLAN
}
