"""
Cut the half-height plaster wall models out of their full-height counterparts.

The half wall families shipped with only a straight model. Every one of their
blockstate variants pointed at it, so a corner or a junction drew a plain run and
the perpendicular arm was left to the neighbour - which reaches the shared face
but stops eleven voxels short of the run inside the junction's own block. That is
the gap you see where two half walls meet at right angles.

The straight half models are exactly clamp(y, 0, 16) of the full-height ones,
with the vertical faces re-cut to the slice of texture that survives. This script
is that transform, and it is checked against the hand-made straights before it
writes anything: if it cannot reproduce those four byte for byte, it refuses to
run, because then it does not understand the art well enough to cut the rest.

    python tools/generate_half_walls.py [--check]

--check verifies and reports without writing.
"""
import argparse
import collections
import io
import json
import os
import sys

HALF = 16.0
VERTICAL = ('north', 'south', 'east', 'west')

ASSETS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      'src', 'main', 'resources', 'assets', 'britannia_mod')
MODELS = os.path.join(ASSETS, 'models', 'block', 'structure', 'plaster')
BLOCKSTATES = os.path.join(ASSETS, 'blockstates')

FAMILIES = [
    'plaster_wall_blank',
    'plaster_wall_and_support_blank',
    'plaster_wall_support_diagonal_east',
    'plaster_wall_support_diagonal_south',
]
JUNCTIONS = ['corner', 'corner_branch_right', 't_junction', 't_junction_branch_right']
Y_FOR_FACING = {'north': 0, 'east': 90, 'south': 180, 'west': 270}

NOTE = ('Half-height cut of {source}: clamp(y, 0, 16) with the vertical faces re-cut to the slice '
        'of texture that survives. Generated by tools/generate_half_walls.py, which proves the '
        'transform against the hand-made _half straight models before writing.')


def slice_uv(uv, rotation, frac0, frac1):
    """Re-cut a vertical face's UV to the fraction of the element's height that survives."""
    u1, v1, u2, v2 = uv
    rot = rotation % 360
    if rot not in (0, 180):
        # A quarter-turned face is one of the timber posts, whose grain runs across it. The
        # hand-cut half models leave those alone and let the grain compress rather than crop away
        # the cap detail, so this does too.
        return list(uv)
    span = v2 - v1
    if rot == 0:
        return [u1, v2 - span * frac1, u2, v2 - span * frac0]
    return [u1, v1 + span * frac0, u2, v1 + span * frac1]


def halve(doc):
    out = json.loads(json.dumps(doc), object_pairs_hook=collections.OrderedDict)
    kept = []
    for element in out.get('elements', []):
        y0, y1 = element['from'][1], element['to'][1]
        low, high = max(0.0, min(HALF, y0)), max(0.0, min(HALF, y1))
        if high - low <= 1e-9:
            continue  # nothing of this element survives the cut
        if abs((high - low) - (y1 - y0)) > 1e-9:
            frac0 = (low - y0) / (y1 - y0)
            frac1 = (high - y0) / (y1 - y0)
            for face, data in element['faces'].items():
                if face in VERTICAL and 'uv' in data:
                    data['uv'] = [round(c, 5) for c in
                                  slice_uv(data['uv'], data.get('rotation', 0), frac0, frac1)]
            element['from'][1] = low
            element['to'][1] = high
            rotation = element.get('rotation')
            if rotation and rotation.get('angle') and 'origin' in rotation:
                # The diagonal braces pivot about a point below the floor, which only makes sense
                # at full height. Bring it back inside the block so the brace still leans across
                # the wall it actually has.
                rotation['origin'][1] = max(0.0, min(HALF, rotation['origin'][1]))
        kept.append(element)
    out['elements'] = kept
    return out


def load(path):
    with io.open(path, encoding='utf-8-sig') as handle:
        return json.load(handle, object_pairs_hook=collections.OrderedDict)


def matches(a, b, tol=1e-3):
    if isinstance(a, dict) and isinstance(b, dict):
        return set(a) == set(b) and all(matches(a[k], b[k], tol) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(matches(x, y, tol) for x, y in zip(a, b))
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(a - b) <= tol
    return a == b


def prove_transform():
    """The straights are already cut by hand, so they are the proof this is the right cut."""
    for family in FAMILIES:
        cut = halve(load(os.path.join(MODELS, family + '_straight.json')))
        hand = load(os.path.join(MODELS, family + '_half.json'))
        if not matches(cut.get('elements'), hand.get('elements')):
            raise SystemExit(
                'refusing to write: cutting %s_straight does not reproduce the hand-made '
                '%s_half, so this transform does not match the art' % (family, family))
    return True


def write_json(path, doc):
    with io.open(path, 'w', encoding='utf-8', newline='\n') as handle:
        json.dump(doc, handle, indent='\t')
        handle.write('\n')


def blockstate_for(family):
    variants = collections.OrderedDict()
    for facing, rotation in Y_FOR_FACING.items():
        for shape in ('straight', 'corner', 't_junction'):
            for branch_right in (False, True):
                suffix = '' if shape == 'straight' else \
                    '_' + shape + ('_branch_right' if branch_right else '')
                entry = collections.OrderedDict()
                entry['model'] = 'britannia_mod:block/structure/plaster/' + family + '_half' + suffix
                if rotation:
                    entry['y'] = rotation
                variants['facing=%s,shape=%s,branch_right=%s'
                         % (facing, shape, str(branch_right).lower())] = entry
    return collections.OrderedDict([('variants', variants)])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='verify without writing')
    args = parser.parse_args()

    prove_transform()
    print('transform reproduces all %d hand-made half straights' % len(FAMILIES))
    if args.check:
        return 0

    for family in FAMILIES:
        for junction in JUNCTIONS:
            source = family + '_' + junction
            doc = halve(load(os.path.join(MODELS, source + '.json')))
            doc['__comment'] = NOTE.format(source=source)
            write_json(os.path.join(MODELS, family + '_half_' + junction + '.json'), doc)
        write_json(os.path.join(BLOCKSTATES, family + '_half.json'), blockstate_for(family))
        print('  cut %s_half: %d junction models + blockstate' % (family, len(JUNCTIONS)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
