package com.seggellion.britannia_mod.banner.placement;

public enum BannerPlacementFailure {
    NONE,
    INVALID_ITEM,
    UNCONFIGURED_BANNER,
    REGISTRY_UNAVAILABLE,
    DEFINITION_MISSING,
    DEFINITION_DISABLED,
    MATERIAL_MISSING,
    MATERIAL_DISABLED,
    PALETTE_MISSING,
    COLOUR_MISSING,
    MOUNT_MISSING,
    MOUNT_DISABLED,
    UNSUPPORTED_MOUNT,
    UNSUPPORTED_ORIENTATION,
    MULTI_BLOCK_PLACEMENT_DEFERRED,
    INVALID_CLICKED_FACE,
    TARGET_OCCUPIED,
    WORLD_BOUND_FAILURE,
    INVALID_WALL_SUPPORT,
    PROTECTED_PLACEMENT,
    BLOCK_ENTITY_CREATION_FAILURE,
    STATE_TRANSFER_FAILURE,
    BLOCK_SET_FAILURE,
    UNEXPECTED_ROLLBACK_FAILURE
}
